[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Truss-101"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
[pypi-dependencies]
certifi = ">=2025.1.31, <2026"
charset-normalizer = ">=3.4.1, <4"
fonttools = ">=4.57.0, <5"
idna = ">=3.10, <4"
kiwisolver = ">=1.4.8, <2"
matplotlib = ">=3.10.1, <4"
packaging = ">=25.0, <26"
pillow = ">=11.2.1, <12"
pyparsing = ">=3.2.3, <4"
pyside2 = ">=5.15.2.1, <6"
python-dateutil = ">=2.9.0.post0, <3"
reportlab = ">=4.4.0, <5"
requests = ">=2.32.3, <3"
shiboken2 = ">=5.15.2.1, <6"
six = ">=1.17.0, <2"
urllib3 = ">=2.4.0, <3"
pyinstaller = ">=6.13.0, <7"
numpy = ">=1.26.4,<2"
