name: Build Executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pixi install

      - name: Build with PyInstaller
        run: pixi run pyinstaller --onefile --windowed main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Truss-101-Executable
          path: dist/main
