name: Build Executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install pixi (Linux/macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Install pixi (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          irm https://pixi.sh/install.ps1 | iex
          echo "$env:USERPROFILE\.pixi\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # Set up Python step might not be strictly necessary if pixi manages it,
      # but keeping it for now ensures a specific Python version is available globally if needed.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13" # Consider if pixi should manage this via pixi.toml

      - name: Install dependencies
        run: pixi install

      - name: Build with PyInstaller
        run: pixi run pyinstaller --onefile --windowed main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Truss-101-Executable-${{ matrix.os }}
          path: |
            dist/main
            dist/main.exe
